### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by yangquan1982** [moby/hyperkit#250]
When I try to build with `make` in macOS 10.14.4, got following errors: 
> cc src/lib/firmware/fbsd.c
src/lib/firmware/fbsd.c:690:7: error: implicit conversion changes signedness: 'unsigned int' to 'int' [-Werror,-Wsign-conversion]
        case MSR_EFER:
             ^~~~~~~~
In file included from src/lib/firmware/fbsd.c:80:
src/include/xhyve/support/specialreg.h:771:18: note: expanded from macro 'MSR_EFER'
#define MSR_EFER        0xc0000080      /* extended features */
                        ^~~~~~~~~~
1 error generated.
make: *** [build/lib/firmware/fbsd.o] Error 1

**Comment by kvn0218** [comment]
getting the same error with my mac that is also on 10.14.4

**Comment by townsend2010** [comment]
I think this is related to #246 which has a PR attached to it that supposedly fixes this issue.  I'm anxiously awaiting for that PR to be merged :)

**Comment by ijc** [comment]
#248 has been merged and I think fixed this, thanks,
